/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Wage;
import Business.Worker;
import Business.WorkerDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hu.ziy
 */
public class PerformJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PerformJPanel
     */
    JPanel userProcessContainer;
    WorkerDirectory workerDirectory;

    public PerformJPanel(JPanel upc, WorkerDirectory wd) {
        initComponents();
        this.userProcessContainer = upc;
        this.workerDirectory = wd;

        typeComboBox.addItem("铺布");
        typeComboBox.addItem("缝头");
        typeComboBox.addItem("烧毛");
        typeComboBox.addItem("压碱");
        typeComboBox.addItem("氧漂");
        typeComboBox.addItem("热熔打底水洗");
        typeComboBox.addItem("溢流");
        typeComboBox.addItem("卷染");
        typeComboBox.addItem("烘干");
        typeComboBox.addItem("定型");
        typeComboBox.addItem("验布整理");
        typeComboBox.addItem("实习期");
        yangpiao.addItem("挡车工");
        yangpiao.addItem("化料工");
        yangpiao.addItem("进出布");
        yangpiao.setVisible(false);
        da.setVisible(false);
        ca.setVisible(false);
        weisheng.setVisible(false);
        caJ.setVisible(false);
        weisheng.addItem("0");
        weisheng.addItem("1");
        weisheng.addItem("2");
        weisheng.addItem("3");
        ca.addItem("0");
        ca.addItem("1");
        ca.addItem("2");
        ca.addItem("3");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        wageButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameTXT = new javax.swing.JTextField();
        genderTXT = new javax.swing.JTextField();
        wageTXT = new javax.swing.JTextField();
        miTXT = new javax.swing.JTextField();
        kind = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        numberTXT = new javax.swing.JTextField();
        calculate = new javax.swing.JButton();
        da = new javax.swing.JLabel();
        caJ = new javax.swing.JLabel();
        weisheng = new javax.swing.JComboBox<>();
        ca = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        yangpiao = new javax.swing.JComboBox<>();
        wTXT = new javax.swing.JTextField();
        cTXT = new javax.swing.JTextField();
        dayangTXT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        da1 = new javax.swing.JLabel();
        da2 = new javax.swing.JLabel();

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel9.setText("jLabel9");

        jLabel1.setFont(new java.awt.Font("方正兰亭超细黑简体", 0, 18)); // NOI18N
        jLabel1.setText("岗位：");

        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });

        wageButton.setText("载入");
        wageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wageButtonActionPerformed(evt);
            }
        });

        confirmButton.setText("确认");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("方正兰亭超细黑简体", 0, 18)); // NOI18N
        jLabel2.setText("姓名");

        jLabel3.setFont(new java.awt.Font("方正兰亭超细黑简体", 0, 18)); // NOI18N
        jLabel3.setText("性别");

        jLabel5.setFont(new java.awt.Font("方正兰亭超细黑简体", 0, 18)); // NOI18N
        jLabel5.setText("工资");

        jLabel6.setFont(new java.awt.Font("方正兰亭超细黑简体", 0, 18)); // NOI18N
        jLabel6.setText("种类");

        jLabel7.setFont(new java.awt.Font("方正兰亭超细黑简体", 0, 18)); // NOI18N
        jLabel7.setText("米数");

        nameTXT.setEnabled(false);
        nameTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTXTActionPerformed(evt);
            }
        });

        genderTXT.setEditable(false);
        genderTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderTXTActionPerformed(evt);
            }
        });

        wageTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wageTXTActionPerformed(evt);
            }
        });

        miTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTXTActionPerformed(evt);
            }
        });

        kind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kindActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("方正兰亭超细黑简体", 0, 18)); // NOI18N
        jLabel8.setText("定员人数");

        numberTXT.setText("3");
        numberTXT.setDoubleBuffered(true);
        numberTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTXTActionPerformed(evt);
            }
        });

        calculate.setText("计算");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        da.setFont(new java.awt.Font("方正兰亭超细黑简体", 0, 18)); // NOI18N
        da.setText("大卫生");

        caJ.setFont(new java.awt.Font("方正兰亭超细黑简体", 0, 18)); // NOI18N
        caJ.setText("擦拱桶");

        jButton1.setText("<<后退");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        wTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wTXTActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("方正兰亭超细黑简体", 0, 18)); // NOI18N
        jLabel4.setText("打样");

        da1.setFont(new java.awt.Font("方正兰亭超细黑简体", 0, 18)); // NOI18N
        da1.setText("次数");

        da2.setFont(new java.awt.Font("方正兰亭超细黑简体", 0, 18)); // NOI18N
        da2.setText("次数");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(caJ)
                                .addComponent(da)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)))
                        .addGap(94, 94, 94)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel8)
                        .addGap(48, 48, 48)
                        .addComponent(numberTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 164, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dayangTXT)
                            .addComponent(ca, 0, 141, Short.MAX_VALUE)
                            .addComponent(weisheng, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kind, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameTXT)
                            .addComponent(genderTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(miTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(wageTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(da2)
                            .addComponent(da1))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(confirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(wageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yangpiao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(wTXT, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cTXT, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(numberTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmButton))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(genderTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(kind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yangpiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(miTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(wageTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calculate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weisheng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(da)
                            .addComponent(wTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(da2))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(caJ))
                    .addComponent(ca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(da1))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayangTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(wageButton))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void wageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wageButtonActionPerformed
        // TODO add your handling code here:
        Worker worker = workerDirectory.addWorker();
        wageJPanel w = new wageJPanel(userProcessContainer, worker);
        userProcessContainer.add("wageJPanel", w);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_wageButtonActionPerformed

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_typeComboBoxActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:     
        for (Worker wr : workerDirectory.getWorkerlist()) {
            nameTXT.setText(wr.getWorkerName());
            genderTXT.setText(wr.getGender());
        }

        Object o = typeComboBox.getSelectedItem();
        int type = 12;
        if (o.equals("铺布")) {
            type = 1;
        }
        if (o.equals("缝头")) {
            type = 2;
        }
        if (o.equals("烧毛")) {
            type = 3;
        }
        if (o.equals("压碱")) {
            type = 4;
        }
        if (o.equals("氧漂")) {
            type = 5;
        }
        if (o.equals("热熔打底水洗")) {
            type = 6;
        }
        if (o.equals("溢流")) {
            type = 7;
        }
        if (o.equals("卷染")) {
            type = 8;
        }
        if (o.equals("烘干")) {
            type = 9;
        }
        if (o.equals("定型")) {
            type = 10;
        }
        if (o.equals("验布整理")) {
            type = 11;
        }
        if (o.equals("实习期")) {
            type = 12;
        }
        switch (type) {
            case 1:
                kind.removeAllItems();
                kind.addItem("130g/m以下半漂");
                kind.addItem("长车不分缸");
                kind.addItem("纱卡63”");
                kind.addItem("细纺布分缸");
                kind.addItem("108*58 防水39”");
                kind.addItem("涤帆布63”");

                break;
            case 2:
                kind.removeAllItems();
                kind.addItem("细纺47");
                kind.addItem("200g以下63”");
                kind.addItem("厚帆布");
                kind.addItem("包边60”以上");
                kind.addItem("包边60”以下");
                kind.addItem("双边60”以上");
                kind.addItem("双边60”以上");
                break;
            case 4:
                kind.removeAllItems();
                kind.addItem("正常");
                kind.addItem("厚帆布");
                kind.addItem("打冷堆");
                break;
            case 5:
                da.setVisible(true);
                ca.setVisible(true);
                weisheng.setVisible(true);
                caJ.setVisible(true);
                yangpiao.setVisible(true);
                kind.removeAllItems();
                kind.addItem("车速50-60");
                kind.addItem("车速30-48");
                kind.addItem("车速30以下");
                kind.addItem("水洗");

        }

    }//GEN-LAST:event_confirmButtonActionPerformed

    private void nameTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTXTActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_nameTXTActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void genderTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderTXTActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_genderTXTActionPerformed

    private void wageTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wageTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wageTXTActionPerformed

    private void miTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miTXTActionPerformed

    private void kindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kindActionPerformed

    private void numberTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTXTActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        Object o = typeComboBox.getSelectedItem();
        if (miTXT.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "设置米数!!", "提示", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Object o1 = kind.getSelectedItem();
            Object o2 = yangpiao.getSelectedItem();
            double wage = 0;
            if (o1.equals("130g/m以下半漂") || genderTXT.equals("男")) {
                wage = (45.5 / (Double.parseDouble(numberTXT.getText()))) * 1.166 * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
                workerDirectory.addWorker().getWageCatolog().addWage().setPerformance(wage);
            }
            if (o1.equals("130g/m以下半漂") || genderTXT.equals("女")) {
                wage = (45.5 / (Double.parseDouble(numberTXT.getText()))) * 1.123 * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("长车不分缸") || genderTXT.equals("男")) {
                wage = (52 / (Double.parseDouble(numberTXT.getText()))) * 1.116 * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("长车不分缸") || genderTXT.equals("女")) {
                wage = (52 / (Double.parseDouble(numberTXT.getText()))) * 1.123 * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("纱卡63”") || genderTXT.equals("男")) {
                wage = (78 / (Double.parseDouble(numberTXT.getText()))) * 1.116 * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("纱卡63”") || genderTXT.equals("女")) {
                wage = (78 / (Double.parseDouble(numberTXT.getText()))) * 1.123 * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }

            if (o1.equals("细纺布分缸") || genderTXT.equals("男")) {
                wage = (65 / (Double.parseDouble(numberTXT.getText()))) * 1.116 * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("细纺布分缸") || genderTXT.equals("女")) {
                wage = (65 / (Double.parseDouble(numberTXT.getText()))) * 1.123 * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("108*58 防水39”") || genderTXT.equals("男")) {
                wage = (78 / (Double.parseDouble(numberTXT.getText()))) * 1.116 * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("108*58 防水39”") || genderTXT.equals("女")) {
                wage = (78 / (Double.parseDouble(numberTXT.getText()))) * 1.123 * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("涤帆布63”") || genderTXT.equals("男")) {
                wage = (130 / (Double.parseDouble(numberTXT.getText()))) * 1.116 * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("涤帆布63”") || genderTXT.equals("女")) {
                wage = (130 / (Double.parseDouble(numberTXT.getText()))) * 1.123 * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("细纺47") || genderTXT.equals("女")) {
                wage = (35.9 / (Double.parseDouble(numberTXT.getText()))) * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("厚帆布") || genderTXT.equals("女")) {
                wage = (51.9 / (Double.parseDouble(numberTXT.getText()))) * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("200g以下63”") || genderTXT.equals("女")) {
                wage = (44.9 / (Double.parseDouble(numberTXT.getText()))) * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("包边60”以上") || genderTXT.equals("女")) {
                wage = (49.4 / (Double.parseDouble(numberTXT.getText()))) * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("包边60”以下") || genderTXT.equals("女")) {
                wage = (39.5 / (Double.parseDouble(numberTXT.getText()))) * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("双边60”以上") || genderTXT.equals("女")) {
                wage = (67.4 / (Double.parseDouble(numberTXT.getText()))) * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("双边60”以下") || genderTXT.equals("女")) {
                wage = (53.9 / (Double.parseDouble(numberTXT.getText()))) * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }
            if (o.equals("烧毛") || genderTXT.equals("女")) {
                wage = (50 / (Double.parseDouble(numberTXT.getText()))) * 1.166 * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }
            if (o.equals("烧毛") || genderTXT.equals("女")) {
                wage = (50 / (Double.parseDouble(numberTXT.getText()))) * 1.123 * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }

            if (o1.equals("正常") || genderTXT.equals("男")) {
                wage = (46.6 / (Double.parseDouble(numberTXT.getText()))) * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("厚帆布") || genderTXT.equals("男")) {
                wage = (69.9 / (Double.parseDouble(numberTXT.getText()))) * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("打冷堆") || genderTXT.equals("男")) {
                wage = (81.6 / (Double.parseDouble(numberTXT.getText()))) * (Double.parseDouble(miTXT.getText()));
                wageTXT.setText(String.valueOf(wage));
            }

            if (o1.equals("车速50-60") || o2.equals("挡车工")) {
                wage = 47.23 * (Double.parseDouble(miTXT.getText())) + (300 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(wTXT.getText()) + (30 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(cTXT.getText());

                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("车速50-60") || o2.equals("化料工")) {
                wage = 39.36 * (Double.parseDouble(miTXT.getText())) + (300 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(wTXT.getText()) + (30 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(cTXT.getText());

                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("车速50-60") || o2.equals("进出布") || genderTXT.equals("男")) {
                wage = 35.42 * (Double.parseDouble(miTXT.getText())) + (300 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(wTXT.getText()) + (30 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(cTXT.getText());

                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("车速50-60") || o2.equals("进出布") || genderTXT.equals("女")) {
                wage = 34.11 * (Double.parseDouble(miTXT.getText())) + (300 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(wTXT.getText()) + (30 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(cTXT.getText());

                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("车速30-48") || o2.equals("挡车工")) {
                wage = 61.41 * (Double.parseDouble(miTXT.getText())) + (300 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(wTXT.getText()) + (30 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(cTXT.getText());

                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("车速30-48") || o2.equals("化料工")) {
                wage = 51.17 * (Double.parseDouble(miTXT.getText())) + (300 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(wTXT.getText()) + (30 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(cTXT.getText());

                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("车速30-48") || o2.equals("进出布") || genderTXT.equals("男")) {
                wage = 46.04 * (Double.parseDouble(miTXT.getText())) + (300 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(wTXT.getText()) + (30 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(cTXT.getText());

                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("车速30-48") || o2.equals("进出布") || genderTXT.equals("女")) {
                wage = 44.35 * (Double.parseDouble(miTXT.getText())) + (300 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(wTXT.getText()) + (30 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(cTXT.getText());

                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("车速30以下") || o2.equals("挡车工")) {
                wage = 94.47 * (Double.parseDouble(miTXT.getText())) + (300 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(wTXT.getText()) + (30 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(cTXT.getText());

                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("车速30以下") || o2.equals("化料工")) {
                wage = 78.73 * (Double.parseDouble(miTXT.getText())) + (300 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(wTXT.getText()) + (30 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(cTXT.getText());

                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("车速30以下") || o2.equals("进出布") || genderTXT.equals("男")) {
                wage = 70.85 * (Double.parseDouble(miTXT.getText())) + (300 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(wTXT.getText()) + (30 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(cTXT.getText());

                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("车速30以下") || o2.equals("进出布") || genderTXT.equals("女")) {
                wage = 68.23 * (Double.parseDouble(miTXT.getText())) + (300 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(wTXT.getText()) + (30 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(cTXT.getText());

                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("水洗") || genderTXT.equals("男")) {
                wage = 148 / (Double.parseDouble(numberTXT.getText())) * 1.166 * (Double.parseDouble(miTXT.getText())) + (300 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(wTXT.getText()) + (30 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(cTXT.getText());

                wageTXT.setText(String.valueOf(wage));
            }
            if (o1.equals("水洗") || genderTXT.equals("女")) {
                wage = 148 / (Double.parseDouble(numberTXT.getText())) * 1.123 * (Double.parseDouble(miTXT.getText())) + (300 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(wTXT.getText()) + (30 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(cTXT.getText());
//   wage = 68.23* (Double.parseDouble(miTXT.getText())) + (300 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(wTXT.getText()) + (30 / (Double.parseDouble(numberTXT.getText()))) * Double.parseDouble(cTXT.getText());

                wageTXT.setText(String.valueOf(wage));
            }

    }//GEN-LAST:event_calculateActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void wTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wTXTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cTXT;
    private javax.swing.JComboBox<String> ca;
    private javax.swing.JLabel caJ;
    private javax.swing.JButton calculate;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel da;
    private javax.swing.JLabel da1;
    private javax.swing.JLabel da2;
    private javax.swing.JTextField dayangTXT;
    private javax.swing.JTextField genderTXT;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> kind;
    private javax.swing.JTextField miTXT;
    private javax.swing.JTextField nameTXT;
    private javax.swing.JTextField numberTXT;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JTextField wTXT;
    private javax.swing.JButton wageButton;
    private javax.swing.JTextField wageTXT;
    private javax.swing.JComboBox<String> weisheng;
    private javax.swing.JComboBox<String> yangpiao;
    // End of variables declaration//GEN-END:variables
}
